version: '3.4'

x-ruby-box: &ruby-box
  platform: linux/amd64
  build:
    context: box
    dockerfile: Dockerfile
    args:
      PG_MAJOR: '13'
      RUBY_VERSION: '2.7.5'
      NODE_MAJOR: '17'
      YARN_VERSION: '1.22.5'
      BUNDLER_VERSION: '2.3.7'
  image: ruby-box:2.7.5
  tmpfs:
    - /tmp
  stdin_open: true
  tty: true
  networks:
    - traefik-public
  environment:
    NODE_ENV: development
    RAILS_ENV: ${RAILS_ENV:-development}
    BOOTSNAP_CACHE_DIR: /usr/local/bundle/_bootsnap
    WEB_CONCURRENCY: 1
    HISTFILE: /app/log/.bash_history
    PSQL_HISTFILE: /app/log/.psql_history
    DOCKERIZED: ${DOCKERIZED:-1}
    WEBPACKER_DEV_SERVER_HOST: packer
  volumes:
    - .:/app:cached
    - rails_cache:/app/tmp/cache
    - bundle:/usr/local/bundle
    - node_modules:/app/node_modules
    - packs:/app/public/packs

services:
  app:
    <<: *ruby-box
    command: bundle exec puma -p 3000 -w 1
    expose:
      - 3000
    networks:
      default:
      traefik-public:
        aliases:
          - app.dev.local
    depends_on:
      - packer
    environment:
      - DATABASE_URL=postgis://postgres:postgres@host.docker.internal:5432/app_db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=HostRegexp(`app.dev.local`)"
      - "traefik.http.routers.app.entrypoints=web"

  shell:
    <<: *ruby-box
    command: bash

  packer:
    <<: *ruby-box
    command: ./bin/webpack-dev-server
    ports:
      - 3035:3035
    environment:
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0

  selenium:
    image: selenium/standalone-chrome:latest # this version should match that of the selenium-webdriver gem (see Gemfile)
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - 4444:4444
    networks:
      - default

  app-test:
    <<: *ruby-box
    environment:
      RAILS_ENV: test
      SELENIUM_URL: http://selenium:4444/wd/hub
      HEADLESS: 'true'
    command: bash
    depends_on:
      - selenium
    networks:
      - default
      - traefik-public

volumes:
  bundle:
  node_modules:
  rails_cache:
  packs:

networks:
  traefik-public:
    external: true
