version: '3.4'
services:
  proxy:
    image: traefik:v3.1.4
    # on my notebook traefik serves on default http https ports
    # this allows natural urls like https://app.dev.local/
    ports:
      - 80:80
      - 443:443
    # /certs and /conf are dedicated known directories in
    # official traefik image.
    # in order to allow traefik to expose docker backend we are
    # mapping docker socket inside.
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik_certs:/certs
      - ./traefik_conf:/conf
    restart: always
    # if traefik supposed to serve real swarm cluster, peram should be specified
    #       --docker.swarmmode
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.watch=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.file.directory=/conf/"
      - "--providers.file.watch=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.db.address=:5432/tcp"
      - "--log.level=DEBUG"
      - "--accessLog"
      - "--api"
      - "--metrics"
      - "--metrics.prometheus"
      - "--providers.docker.network=traefik-public"
    networks:
      traefik-public:
    # traefik configuration via labels
    # expose traefik dashboard under address http://proxy.dev.local
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`proxy.dev.local`)"
      - "traefik.http.routers.traefik.entrypoints=web"
      - "traefik.http.routers.traefik.service=api@internal"
      # pgvector route
      - "traefik.tcp.routers.db.entrypoints=db"
      - "traefik.tcp.routers.db.tls={}"
      - "traefik.tcp.routers.db.service=pgvector"

  pgvector:
    image: pgvector/pgvector:pg16
    container_name: pgvector
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - ALLOW_IP_RANGE=0.0.0.0/0
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5434:5432
    networks:
      traefik-public:
        aliases:
          - db.dev.local
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.pgvector.rule=HostSNI(`*`)"
      - "traefik.tcp.services.pgvector.loadbalancer.server.port=5432"
      - "traefik.tcp.routers.pgvector.entrypoints=db"
      - "traefik.tcp.routers.pgvector.tls=false"
    restart: on-failure

volumes:
  db_data:

networks:
  traefik-public:
    external: true
